import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from './Components/Nav'
import Authenbutton from './Components/Authenbutton'
import Header from './Components/Header'
import Treding from './Components/Trending'
export default function Home() {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid md:grid-cols-5 ">
        <Nav/>
        <main className="col-span-4 bg-cyan-100">
          <p>Main Content</p>

        <Authenbutton/>
        <Header/>
        <Treding/>
        </main>
      </div>



     
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  )
}
